import { IoK8sApiFlowcontrolV1beta3PriorityLevelConfigurationConditionModelOptions as IoK8sApiFlowcontrolV1beta3PriorityLevelConfigurationCondition } from '../IoK8sApiFlowcontrolV1beta3PriorityLevelConfigurationCondition';

export interface IoK8sApiFlowcontrolV1beta3PriorityLevelConfigurationStatusModelOptions {
  conditions?: Array<IoK8sApiFlowcontrolV1beta3PriorityLevelConfigurationCondition>;
}
