import { IoK8sApiCoreV1AWSElasticBlockStoreVolumeSourceModelOptions as IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource } from '../IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource';
import { IoK8sApiCoreV1AzureDiskVolumeSourceModelOptions as IoK8sApiCoreV1AzureDiskVolumeSource } from '../IoK8sApiCoreV1AzureDiskVolumeSource';
import { IoK8sApiCoreV1AzureFilePersistentVolumeSourceModelOptions as IoK8sApiCoreV1AzureFilePersistentVolumeSource } from '../IoK8sApiCoreV1AzureFilePersistentVolumeSource';
import { IoK8sApiCoreV1CSIPersistentVolumeSourceModelOptions as IoK8sApiCoreV1CSIPersistentVolumeSource } from '../IoK8sApiCoreV1CSIPersistentVolumeSource';
import { IoK8sApiCoreV1CephFSPersistentVolumeSourceModelOptions as IoK8sApiCoreV1CephFSPersistentVolumeSource } from '../IoK8sApiCoreV1CephFSPersistentVolumeSource';
import { IoK8sApiCoreV1CinderPersistentVolumeSourceModelOptions as IoK8sApiCoreV1CinderPersistentVolumeSource } from '../IoK8sApiCoreV1CinderPersistentVolumeSource';
import { IoK8sApiCoreV1FCVolumeSourceModelOptions as IoK8sApiCoreV1FCVolumeSource } from '../IoK8sApiCoreV1FCVolumeSource';
import { IoK8sApiCoreV1FlexPersistentVolumeSourceModelOptions as IoK8sApiCoreV1FlexPersistentVolumeSource } from '../IoK8sApiCoreV1FlexPersistentVolumeSource';
import { IoK8sApiCoreV1FlockerVolumeSourceModelOptions as IoK8sApiCoreV1FlockerVolumeSource } from '../IoK8sApiCoreV1FlockerVolumeSource';
import { IoK8sApiCoreV1GCEPersistentDiskVolumeSourceModelOptions as IoK8sApiCoreV1GCEPersistentDiskVolumeSource } from '../IoK8sApiCoreV1GCEPersistentDiskVolumeSource';
import { IoK8sApiCoreV1GlusterfsPersistentVolumeSourceModelOptions as IoK8sApiCoreV1GlusterfsPersistentVolumeSource } from '../IoK8sApiCoreV1GlusterfsPersistentVolumeSource';
import { IoK8sApiCoreV1HostPathVolumeSourceModelOptions as IoK8sApiCoreV1HostPathVolumeSource } from '../IoK8sApiCoreV1HostPathVolumeSource';
import { IoK8sApiCoreV1ISCSIPersistentVolumeSourceModelOptions as IoK8sApiCoreV1ISCSIPersistentVolumeSource } from '../IoK8sApiCoreV1ISCSIPersistentVolumeSource';
import { IoK8sApiCoreV1LocalVolumeSourceModelOptions as IoK8sApiCoreV1LocalVolumeSource } from '../IoK8sApiCoreV1LocalVolumeSource';
import { IoK8sApiCoreV1NFSVolumeSourceModelOptions as IoK8sApiCoreV1NFSVolumeSource } from '../IoK8sApiCoreV1NFSVolumeSource';
import { IoK8sApiCoreV1ObjectReferenceModelOptions as IoK8sApiCoreV1ObjectReference } from '../IoK8sApiCoreV1ObjectReference';
import { IoK8sApiCoreV1PhotonPersistentDiskVolumeSourceModelOptions as IoK8sApiCoreV1PhotonPersistentDiskVolumeSource } from '../IoK8sApiCoreV1PhotonPersistentDiskVolumeSource';
import { IoK8sApiCoreV1PortworxVolumeSourceModelOptions as IoK8sApiCoreV1PortworxVolumeSource } from '../IoK8sApiCoreV1PortworxVolumeSource';
import { IoK8sApiCoreV1QuobyteVolumeSourceModelOptions as IoK8sApiCoreV1QuobyteVolumeSource } from '../IoK8sApiCoreV1QuobyteVolumeSource';
import { IoK8sApiCoreV1RBDPersistentVolumeSourceModelOptions as IoK8sApiCoreV1RBDPersistentVolumeSource } from '../IoK8sApiCoreV1RBDPersistentVolumeSource';
import { IoK8sApiCoreV1ScaleIOPersistentVolumeSourceModelOptions as IoK8sApiCoreV1ScaleIOPersistentVolumeSource } from '../IoK8sApiCoreV1ScaleIOPersistentVolumeSource';
import { IoK8sApiCoreV1StorageOSPersistentVolumeSourceModelOptions as IoK8sApiCoreV1StorageOSPersistentVolumeSource } from '../IoK8sApiCoreV1StorageOSPersistentVolumeSource';
import { IoK8sApiCoreV1VolumeNodeAffinityModelOptions as IoK8sApiCoreV1VolumeNodeAffinity } from '../IoK8sApiCoreV1VolumeNodeAffinity';
import { IoK8sApiCoreV1VsphereVirtualDiskVolumeSourceModelOptions as IoK8sApiCoreV1VsphereVirtualDiskVolumeSource } from '../IoK8sApiCoreV1VsphereVirtualDiskVolumeSource';

export interface IoK8sApiCoreV1PersistentVolumeSpecModelOptions {
  accessModes?: Array<string>;
  awsElasticBlockStore?: IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource;
  azureDisk?: IoK8sApiCoreV1AzureDiskVolumeSource;
  azureFile?: IoK8sApiCoreV1AzureFilePersistentVolumeSource;
  capacity?: { [key: string]: string };
  cephfs?: IoK8sApiCoreV1CephFSPersistentVolumeSource;
  cinder?: IoK8sApiCoreV1CinderPersistentVolumeSource;
  claimRef?: IoK8sApiCoreV1ObjectReference;
  csi?: IoK8sApiCoreV1CSIPersistentVolumeSource;
  fc?: IoK8sApiCoreV1FCVolumeSource;
  flexVolume?: IoK8sApiCoreV1FlexPersistentVolumeSource;
  flocker?: IoK8sApiCoreV1FlockerVolumeSource;
  gcePersistentDisk?: IoK8sApiCoreV1GCEPersistentDiskVolumeSource;
  glusterfs?: IoK8sApiCoreV1GlusterfsPersistentVolumeSource;
  hostPath?: IoK8sApiCoreV1HostPathVolumeSource;
  iscsi?: IoK8sApiCoreV1ISCSIPersistentVolumeSource;
  local?: IoK8sApiCoreV1LocalVolumeSource;
  mountOptions?: Array<string>;
  nfs?: IoK8sApiCoreV1NFSVolumeSource;
  nodeAffinity?: IoK8sApiCoreV1VolumeNodeAffinity;
  persistentVolumeReclaimPolicy?: string;
  photonPersistentDisk?: IoK8sApiCoreV1PhotonPersistentDiskVolumeSource;
  portworxVolume?: IoK8sApiCoreV1PortworxVolumeSource;
  quobyte?: IoK8sApiCoreV1QuobyteVolumeSource;
  rbd?: IoK8sApiCoreV1RBDPersistentVolumeSource;
  scaleIO?: IoK8sApiCoreV1ScaleIOPersistentVolumeSource;
  storageClassName?: string;
  storageos?: IoK8sApiCoreV1StorageOSPersistentVolumeSource;
  volumeAttributesClassName?: string;
  volumeMode?: string;
  vsphereVolume?: IoK8sApiCoreV1VsphereVirtualDiskVolumeSource;
}
