import { IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentationModelOptions as IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation } from '../IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation';
import { IoK8sApiextensionsApiserverPkgApisApiextensionsV1ValidationRuleModelOptions as IoK8sApiextensionsApiserverPkgApisApiextensionsV1ValidationRule } from '../IoK8sApiextensionsApiserverPkgApisApiextensionsV1ValidationRule';

export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsModelOptions {
  ref?: string;
  schema?: string;
  additionalItems?: any;
  additionalProperties?: any;
  allOf?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps>;
  anyOf?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps>;
  _default?: any;
  definitions?: { [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps };
  dependencies?: { [key: string]: any };
  description?: string;
  _enum?: Array<any>;
  example?: any;
  exclusiveMaximum?: boolean;
  exclusiveMinimum?: boolean;
  externalDocs?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation;
  format?: string;
  id?: string;
  items?: any;
  maxItems?: number;
  maxLength?: number;
  maxProperties?: number;
  maximum?: number;
  minItems?: number;
  minLength?: number;
  minProperties?: number;
  minimum?: number;
  multipleOf?: number;
  not?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps;
  nullable?: boolean;
  oneOf?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps>;
  pattern?: string;
  patternProperties?: { [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps };
  properties?: { [key: string]: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps };
  required?: Array<string>;
  title?: string;
  type?: string;
  uniqueItems?: boolean;
  xKubernetesEmbeddedResource?: boolean;
  xKubernetesIntOrString?: boolean;
  xKubernetesListMapKeys?: Array<string>;
  xKubernetesListType?: string;
  xKubernetesMapType?: string;
  xKubernetesPreserveUnknownFields?: boolean;
  xKubernetesValidations?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1ValidationRule>;
}
