import { IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceConditionModelOptions as IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition } from '../IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition';

export interface IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatusModelOptions {
  conditions?: Array<IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition>;
}
